<?php

/**
 * This file is automatically generated. Use 'phutil_mapper.php' to rebuild it.
 * @generated
 */

phutil_register_library_map(array(
  'class' =>
  array(
    'JIRAMailListener' => 'src',
    'ThriftMarkGenerated' => 'src',
  ),
  'function' =>
  array(
  ),
  'requires_class' =>
  array(
    'JIRAMailListener' => 'PhutilEventListener',
    'ThriftMarkGenerated' => 'PhutilEventListener',
  ),
  'requires_interface' =>
  array(
  ),
));
